### ISSUE TITLE
Project Part-2 Scores

### ISSUE THREAD

**Issue by AbdulAli** [CMPUT301F22T03/JoyfulMealPlanning#56]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | Final   comments
-- | -- | -- | -- | -- | -- | -- | -- | --
Tool Practices | Product   Backlog | Object-Oriented   Analysis | User   Interface Mockup and Storyboard | Other
3 | Excellent.   Keep this up until the end. start using branches for each issue. | 3 | ✓   Numbered, tracked, and organized requirements     ✓Comprehensive requirements     ✓ Complete story point estimates     ✓ Complete risk levels     ✓ Displays understanding of requirements specification/elicitation     ✘ Requirements noted for half-way checkpoint (Please set a milestone for   the half-way checkpoint stories) | 3 | •   Clear, readable, consistent, and organized: yes     • Covers key classes: yes     • Complete responsibilities: yes     • Complete collaborators: yes     • Object-oriented: yes     • Cohesive classes: yes     • Coupling managed: yes     Comments: Attaching a photo is a UserStory related to the Recipe, not the   Ingredient. CRC card is part of UML. Use proper notations. You don’t need to   provide headings such as responsibilities and collaborators. Use class name   (following Java conventions). | 3 | Excellent |  

</body>

</html>

**Comment by AbdulAli** [comment]
Hi guys @Mashiad-Hasan  @fzhu886  @LittleWhiteVeryWhite  @ZhaoqiMa 
Please tag the other team members as i cant seem to find them on the tagging list.
Please create a separate issue to address each feedback, thanks.

**Comment by BorisMeng** [comment]
Hello @AbdulAli , these are the two team members can't find on tagging list @YuxuanYang2002 @BorisMeng 

- [x] #65  issue has been fixed and closed

**Comment by QiaosongDeng** [comment]
@QiaosongDeng This is me
